### ISSUE TITLE
Max error: failed to create k4abt tracker! (dp.kinect3 help patch)

### ISSUE THREAD

**Issue by acousmatician** [diablodale/dp.kinect3#2]
I have running Azure Kinect with dp.kinect3 in Max. When running the dp.kinect3 help patch, it works fine on the first tab only ('kp.kinect3'). When running any of the other tabs, I get the error: 'Error opening 000314601512 sensor: Failed to create k4abt tracker!' in the Max console.

I have re-installed ('fixed') the Azure SDK. Running k4abt_simple_3d_viewer.exe. (in /tools) works fine. The first tab in the dp.kinect3 help patch works fine.

I am running dp.kinect3 in 'trial' mode

**DEVICE**
Device name WNB2100046
Full device name WNB2100046.ad.bangor.ac.uk
Processor Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM 16.0 GB (15.8 GB usable)
Device ID 0158115B-BEA7-4C95-A93A-BBF45B8C232E
Product ID 00329-10130-20890-AA287
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**SYSTEM**
Edition Windows 10 Enterprise
Version 20H2
Installed on ‎04/‎05/‎2021
OS build 19042.928
Experience Windows Feature Experience Pack 120.2212.551.0

**MAX version** 8.2.1 (2f7eaf31afd) (x64 windows)

**OUTPUT FROM MAX CONSOLE**
![Screenshot 2022-01-20 103054](https://user-images.githubusercontent.com/98091417/150325288-f72e5420-9a29-4ed2-9097-1c47622166c6.png)

(The three errors at the end represent three attempts to run the help patch tabs. An error is thrown whenever the toggle is checked. This does not happen on the first tab.)

**dp.kinec3 FOLDER**
![Screenshot 2022-01-20 095704b](https://user-images.githubusercontent.com/98091417/150326028-ca04c1c9-f610-43d3-a533-87943f98b40a.png)

**Comment by diablodale** [comment]
Thank you. An `Error 126` is an error from the Windows OS itself. It almost always means the OS could not load a DLL it needs for the app/plugin. That very first line in your screenshot is likely the moment of failure and then its cascades to later issues.

I see some others are having similar problems on Max 8 with other plugins. Not yet clear...
https://cycling74.com/forums/error-126-loading-external
https://cycling74.com/forums/%22error-126-loading-external-jit-viddll-engine%22-in-windows-standalone-on-some-machines

To setup similar on my computers, I have a few more questions

1. Is Max 8 itself registered?
2. How do you start Max? What is the specific sequence of things you type or click that start Max?
3. How do you start the dp.kinect3 help patch? What is the specific sequence of things you type or click that open the help patch?
4. Please restart Max. Open the dp.kinect3 help patch. Click on the 'body joints' tab. Then add verbose to the kinect objects like `(dp.kinect3 @skeletonformat 1 @skeleton 1 @verbose 1)`. Click the (open) button directly above it. Now please copy/paste the contents of the entire Max console back to this issue. You might need to scroll to get it all.

**Comment by acousmatician** [comment]
1. Good point. It was in trial mode. I have now authorised. No change.
2. Usually from the search bar, either 'Top apps' or 'Best match'
3. Usually from File>Open recent Patcher in Max
4. @verbose produces no info, just the same error 'Error opening 000314601512 sensor: Failed to create k4abt tracker!'
It seems just using any jit. object produces the Error 126. So that does seem like a Max installation problem.

**BUT** I have an identical machine, and set things up on that - including installing Max. Everything works fine with this machine - no jit. error and dp.kinect3 works as it should. So that's great. However, the hand tracking frame rate (if that's the right term) in the body joints and MIDI help tabs is around 5Hz. That seems really slow, and not really usable for my purposes, and the qmetro at 30Hz suggest it should be a lot faster. The machine (as previously set out above) should be quite capable. In the wiki you mention getting performance improvements by experimenting with settings such as @skelcompute. Are there any such things I could try? (For example, I don't know what @skelcompute options there are.) (And the k4abt_simple3d_viewer.exe that comes with the SDK is even slower - about 1.5Hz.) Thanks for your help!

**Comment by diablodale** [comment]
Machine 1 seems to be errant. Since you are unable to use any `jit` objects on it, I recommend you contact Max support so they can help you get your Max installation working correctly on that computer. That basic jit functionality needs to first work. https://support.cycling74.com/

Machine 2 appears to have a working copy of Max. The system requirements for dp.kinect3 are at https://github.com/diablodale/dp.kinect3/wiki#hardware-and-download-requirements. Please note that the link that goes to Microsoft is a long page with many requirements. The requirements for the basic Azure sensor are near the top. The additional requirements for Body Tracking are further down the page.

Max is a visual patching environment so the values for settings like `skelcompute` and `opencl` can be seen using the Max inspector or Max attrui. I prefer attrui since I can see them easily in my patch. You can briefly read about the performance tuning settings in the `INSTALL.md` file included in your download.

In the `CHANGELOG.md` also in the ZIP download is a section "#### Body tracking details" which has more information on specifics. Everyone's computers and hardware are different so you will need to try the different settings to see which one performs best on your CPU and GPU(s). For example, your default GPU might be an integrated low-power GPU and that may not meet Microsoft's requirements for body tracking. For example, I get ~5fps using my laptops integrated intel gpu. But if I switch that to my laptop's discrete nvidia gpu, I get ~30fps. If you have two GPUs in your computer, be sure to read the details on how to select the specific GPU in that section above.

Most all modern laptops can use opencl. I recommend you set it to `1` as that is often a safe and well performing choice. You can see all the choices for `opencl` using the Max inspector or an attrui. As a tip...the integrated GPUs on most laptops typically do very well as the choice for `opencl`.

Oh and I already doc'd some of this at https://github.com/diablodale/dp.kinect3/wiki#advanced-gpu-and-computing-setup

**Comment by acousmatician** [comment]
Thank you for such a detailed response Dale, that’s very helpful
Andrew

**Comment by acousmatician** [comment]
Thank you, that was massively helpful. Cuda seemed to do the trick. Tensor was similar, but will avoid because of the memory leak.
I got up <30 fps, and I found I could get >50 fps if I set the metro to 50Hz. Setting it to 60Hz made the fps fall back to about 25-30.

I will take up the issue on the other machine with Cycling and our IT people.

Thanks for a great job with this. You must get asked this a lot, but you’re not thinking of a Mac version any time soon? 🙂

**Comment by diablodale** [comment]
Great to hear. :-)

* It is not possible to get more than 30 _unique_ frames/second. The Kinect camera itself captures a maximum of 30fps. Any rate faster is duplicated work/frames. The setting `@unique 1` will prevent dp.kinect3 processing duplicate frames. Your solution may or may-not want these duplicates. You have choice :-)
* A tip in case above was not a typo... when working with jit objects and dp.kinect, always use a qmetro (not metro).
* I suspect you have two GPUs. The default gpu number `0` is a power-saving Intel GPU, and the other gpu number `1` is the Nvidia. Glad `@skelcompute cuda` works for you. Perhaps also test `@skelcompute directml 1`. That will attempt to use the "directml" approach on the NVidia GPU. The attrui doesn't allow two values like that. Instead, you can send that as a message or type it directly on the object like (dp.kinect3 @skelcompute directml 1)
* Mac is not possible at this time. Microsoft does not provide drivers/software for Kinect Azure and its body tracking to run on the Mac.

Happy patching!

**Comment by geckohooks** [comment]
Hi there, I'm previewing dp.kinect3 and struggled with the same issue. (With no Error 126 btw). Looking through your documentation I noticed I had failed to include dnn_model_2_0_lite_op11.onnx (although I did have dnn_model_2_0_op11.onnx in there). When I put the lite doc in, it all worked a treat!
